<a href="https://colab.research.google.com/github/mfza0/Deep_Learning/blob/main/pytorch_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch

In [8]:
my_torch = torch.arange(15)
my_torch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
my_torch1 = my_torch.reshape(3,5)
my_torch1

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [12]:
my_torch2 = my_torch.reshape(1,5,3)
my_torch2

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]]])

In [13]:
d3 = torch.arange(8)
d3

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [15]:
d3 = d3.reshape(2,2,2)
d3

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])

In [21]:
d0 = torch.zeros(3)
d0

tensor([0., 0., 0.])