<a href="https://colab.research.google.com/github/mfza0/Deep_Learning/blob/main/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch

In [8]:
my_torch = torch.arange(15)
my_torch

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
my_torch1 = my_torch.reshape(3,5)
my_torch1

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [12]:
my_torch2 = my_torch.reshape(1,5,3)
my_torch2

tensor([[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11],
         [12, 13, 14]]])

In [13]:
d3 = torch.arange(8)
d3

tensor([0, 1, 2, 3, 4, 5, 6, 7])

In [15]:
d3 = d3.reshape(2,2,2)
d3

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])

In [21]:
d0 = torch.zeros(3)
d0

tensor([0., 0., 0.])

In [22]:
#Tensor Math Operations
import numpy as np

In [23]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


In [24]:
#Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [25]:
#Addition longhand
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [26]:
#Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [27]:
#sub longhand
torch.sub(tensor_b,tensor_a)

tensor([4, 4, 4, 4])

In [28]:
#Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [29]:
torch.mul(tensor_a,tensor_b)

tensor([ 5, 12, 21, 32])

In [30]:
#division
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [31]:
torch.div(tensor_b,tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [32]:
#Remainder modulo
tensor_b%tensor_a

tensor([0, 0, 1, 0])

In [33]:
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [34]:
#exponents / power
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])

In [35]:
#another way to write longhand
tensor_a.add(tensor_b)
#tensor_a.sub...
#tensor_a.mul...etc

tensor([ 6,  8, 10, 12])

In [36]:
#reassignment
tensor_a +tensor_b

tensor([ 6,  8, 10, 12])

In [37]:
tensor_a

tensor([1, 2, 3, 4])

In [38]:
tensor_a.add_(tensor_b) #tensor_a = tensor_a +tensor_b

tensor([ 6,  8, 10, 12])

In [39]:
tensor_a

tensor([ 6,  8, 10, 12])